FROM ubuntu:24.04@sha256:4fbb8e6a8395de5a7550b33509421a2bafbc0aab6c06ba2cef9ebffbc7092d90

ARG DEBIAN_FRONTEND=noninteractive
ARG SLEUTHKIT_VERSION=4.12.1+dfsg-1.1ubuntu2

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates file "sleuthkit=${SLEUTHKIT_VERSION}" \
    && rm -rf /var/lib/apt/lists/*

CMD ["mmls", "-V"]
